# Generated by Django 2.0.3 on 2019-02-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
