# Generated by Django 2.0.3 on 2019-02-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_userfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='name',
        ),
    ]
